PeculiarVentures/GammaCV

- README.md
Update image URLs so they are available on third-party resources, such as npmjs
> Update images URLs in README.md

- app/sources/config.json
- app/src/examples/pc_lines.js
- lib/ops/index.js
- lib/ops/pclines/index.js
> pc lines transform changes

- app/bundler/docs/inline_parse.js
> Update regex for link

- app/sources/docs/get_started.md
Fixed some grammar / spelling errors. Added an example for pipelining operations.
> Updates to getting started guide

- CHANGELOG.md
- app/src/examples/downsample.js
- app/src/examples/upsample.js
- lib/ops/downsample/index.js
- lib/ops/downsample/kernel.glsl
- lib/ops/upsample/index.js
- test/ops/downsample.spec.js
- Fix https://github.com/PeculiarVentures/GammaCV/issues/32, make downsample op RGBA friendly
- Fix typos in error messages
- Update example, to make it colorful
- Add test for downsample operation.
> Downsample operation enhancements

- app/bundler/docs/inline_parse.js
- app/bundler/docs/process_js.js
- app/sources/docs/create_operation.md
- app/sources/docs/get_started.md
- app/src/components/docs/usage_part/props_list/index.jsx
- app/src/components/docs/usage_part/props_list/styles/index.sass
- lib/ops/adaptive_threshold/index.js
- lib/ops/canny_edges/index.js
- lib/ops/pclines/index.js
- lib/ops/sobel_operator/index.js
- lib/ops/swt/index.js
- lib/program/tensor.js
- Fix https://github.com/PeculiarVentures/GammaCV/issues/34
- Fix types of methods in Tensor
- Fix argument's types and their descriptions in some operations
- Include links to documentation of related operations
- Fix parsing of mentions
> Documentation fixes and enhancements

- app/src/components/footer/index.jsx
`pentatonica.co@gmail.com` changed to: `info@peculiarventures.com`
> Get in touch email update

- CHANGELOG.md
- lib/program/kernel_constructor.js
KernelConstructor: make arguments of the main function in glsl optional in main function check.
> Change kernel constructor main func check

- CHANGELOG.md
- lib/program/operation.js
Enhance performance when float polyfill is not needed.
> Performance enhancement

- CHANGELOG.md
- lib/program/session.js
> Changed error threw from not initiated session

- CHANGELOG.md
- lib/io/canvas.js
- lib/io/image.js
- lib/io/video.js
- lib/program/environment.js
- lib/program/session.js
- lib/utils.js
- test/utils.spec.js
Fixes https://github.com/PeculiarVentures/GammaCV/issues/76.
This PR adds support for the WebWorker environment via OffscreenCanvas.
Current status: preparing an automated test.
> Add support for offscreen canvas in webworker environment

- CHANGELOG.md
- lib/index.d.ts
- lib/ops/skin_test/index.js
1. Fix CaptureVideo.start return type (https://github.com/PeculiarVentures/GammaCV/issues/91).
2. Fix typo in comment
3. Add copyright.
> Fix typings file issues

- app/src/components/highlight/index.tsx
> App: Fixed extra mark tags in search Highlight

- .circleci/config.yml
Update image to actual node LTS version.
> Update CI environment

- app/package-lock.json
- package-lock.json
This PR updates dev-dependencies for the website and lib to treat security vulnerabilities in that development dependencies.
> Update dependencies lib and app dev dependencies

- app/src/pages/main/index.module.sass
This is a minor fix of a bug that appears on https://github.com/PeculiarVentures/GammaCV/pull/102.
This PR does not affect the lib in any way.
> App: Fix animation on main page

- app/locales/en.json
- app/sources/docs/config.json
- app/src/pages/docs/index.module.sass
- lib/ops/histogram/index.js
- lib/ops/histogram_equalization/index.js
- lib/ops/perspective_projection/index.js
- Enhance & enable documentation for `histogram` and `histogramEqualization` operations;
- Enhance & enable documentation for `perspectiveProjection` operation.
> Enhance Documentation

- app/package-lock.json
This PR bumps app dependencies to treat dependency volnurabilities.
> Bump app deps

- .circleci/config.yml
Fix https://github.com/PeculiarVentures/GammaCV/issues/168.
> Update CI browser-tool org dependency

- app/package-lock.json
- app/package.json
- package-lock.json
Update dev dependencies to keep them up to date and fix transient dependencies' security vulnerabilities.
> App/Lib: Update development dependencies

- app/next.config.js
- app/pages/docs.tsx
Fixing docs root page redirect based on GitHub pages and next static export limitations.
> App: Fix redirect from docs index to get started

- app/pages/_document.tsx
Part of https://github.com/orgs/PeculiarVentures/projects/1#card-87316348
> UI: Make `helpukrainewinwidget` collapsed by default. Disabled analytics loading for it 

- app/next.config.js
- app/package-lock.json
- app/package.json
- app/src/components/header/index.tsx
- app/src/components/sidebar/sidebar_group.tsx
- app/src/pages/docs/index.tsx
- app/src/pages/example/index.tsx
- app/src/pages/examples/example_item.tsx
Based on https://github.com/PeculiarVentures/GammaCV/pull/189.
Contains additional migration steps.
> App: Update Website Dependencies

- lib/ops/skin_test/index.js
- lib/ops/sliding_window/index.js
Fix https://github.com/PeculiarVentures/GammaCV/issues/201.
Includes minor spelling & typo fixes.
> Fix todo comments appears on docs website

- package-lock.json
This change will not trigger the library release, since only dev dependencies are updated.
> Bump dev dependencies to fix vulnerabilities. Library is not affected
